### ISSUE TITLE
How to handle invalid char ?

### ISSUE THREAD

**Issue by momala454** [box/spout#733]
i have an xlsx file containing an invalid char, which make the code to crash. How do I ignore that character ?

```
  php: PHP Warning:  XMLReader::expand(): zip:///home/extra......aine-27.xlsx#xl/sharedStrings.xml:51: parser error : Char 0xFFFF out of allowed range in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Warning:  XMLReader::expand(): >Ac.....nbspspanp, in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Warning:  XMLReader::expand():                                                                                ^ in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Warning:  XMLReader::expand(): zip:///home/extra......maine-27.xlsx#xl/sharedStrings.xml:51: parser error : PCDATA invalid Char value 65535 in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Warning:  XMLReader::expand(): >Ac.....onbspspanp, in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Warning:  XMLReader::expand():                                                                                ^ in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Warning:  XMLReader::expand(): An Error Occurred while expanding  in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 185
  php: PHP Fatal error:  Uncaught Error: Call to a member function getElementsByTagName() on bool in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php:186
  php: Stack trace:
  php: #0 /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php(119): Box\Spout\Reader\XLSX\Manager\SharedStringsManager->processSharedStringsItem(Object(Box\Spout\Reader\Wrapper\XMLReader), 7760)
  php: #1 /home/vendor/box/spout/src/Spout/Reader/XLSX/Reader.php(92): Box\Spout\Reader\XLSX\Manager\SharedStringsManager->extractSharedStrings()
  php: #2 /home/vendor/box/spout/src/Spout/Reader/ReaderAbstract.php(127): Box\Spout\Reader\XLSX\Reader->openReader('/...')
  php: #3 /home/import.php(102): Box\Spout\Reader\ReaderAbstract->open('/...')
  php: #4 {main}
  php:   thrown in /home/vendor/box/spout/src/Spout/Reader/XLSX/Manager/SharedStringsManager.php on line 186
```

**Comment by madflow** [comment]
Please share the file in question.

**Comment by momala454** [comment]
[file.xlsx](https://github.com/box/spout/files/4369095/file.xlsx)

**Comment by momala454** [comment]
hello please tell me when you got the file so i can delete it

**Comment by madflow** [comment]
We need a defect file for the test case. Maybe you can extract only the relevant part an anonymize it? I do not have MS Excel. When I save it with Libreoffice - the error goes away...

**Comment by momala454** [comment]
i posted the file
i do
$reader = ReaderEntityFactory::createReaderFromFile("the file");
		$reader->open('the file ...");

it crashes when doing open()

**Comment by madflow** [comment]
In order to maximize the chances that someone picks this up is a file with minimal information that makes the reader crash. You posted a complete non-anonymized file. A minimal anonymized file is needed. I suspect rows with `Accueil | Women Safe` in it. You will have to provide this file.

**Comment by momala454** [comment]
i can't make  a new file or edit the file, i receive that file, i didn't generated it

**Comment by momala454** [comment]
hi did you fixed it ?

**Comment by adrilo** [comment]
No this is not fixed. It's an old issue and I don't see any file here that could help debugging so I closed the issue.

**Comment by momala454** [comment]
at the time of posting the issue i put the file but as it could contains confidential info i removed it once madflow got it
and i couldn't generate a new file
